# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-10 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_auto_20171110_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='patients',
            field=models.ManyToManyField(default=None, to='clinic.Patient'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='visits',
            field=models.ManyToManyField(default=None, to='clinic.Visit'),
        ),
    ]
