# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-17 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_auto_20171117_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='phone_num',
            field=models.IntegerField(default='18005000000'),
        ),
    ]
