# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-25 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0006_auto_20171117_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='photo_ID',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
