# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-25 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0007_patient_photo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='blood_type',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='patient',
            name='photo_ID',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sex',
            field=models.IntegerField(default=0),
        ),
    ]
