# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-25 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0013_auto_20171125_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='recommendation',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='symptoms',
            field=models.TextField(blank=True),
        ),
    ]
